apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: isuruk1/users
      context: users
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: isuruk1/courses
      context: courses
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
<<<<<<< HEAD
    - image: akilaelladeniya/reviews
      context: reviews
=======
    - image: sandarujayathilaka98425/learner
      context: learner
>>>>>>> deploy
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
<<<<<<< HEAD
=======
    - image: sandarujayathilaka98425/order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: sandarujayathilaka98425/cart
      context: cart
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

           

    
>>>>>>> deploy
