apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: sandarujayathilaka98425/cart
          env:
            - name: MONGO_URI
              value: mongodb+srv://sandaru:sandaru123@eshopping-api.rumhgfn.mongodb.net/?retryWrites=true&w=majority
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  selector:
    app: cart
  ports:
    - name: cart
      protocol: TCP
      port: 4000
      targetPort: 4000
