apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
        - name: courses
          image: isuruk1/courses
          env:
            - name: MONGO_URI
              value: mongodb+srv://user:user123@project.6kognk6.mongodb.net/micro
            - name: CLOUD_NAME
              value: djtoyeee2
            - name: CLOUD_KEY
              value: "576275933435118"
            - name: CLOUD_KEY_SECRET
              value: QbX7S_wSRKKck5ZfINJMgKI1ydk
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: courses-srv
spec:
  selector:
    app: courses
  ports:
    - name: courses
      protocol: TCP
      port: 4000
      targetPort: 4000
